name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull request to main

jobs:
  # Job for testing the application
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Set the Node.js version for the project

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Make sure your test script is defined in package.json

  # Job for building Docker image
  docker-build:
    runs-on: ubuntu-latest
    needs: test  # This job will run only after the test job succeeds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker build -t your-username/your-app-name:latest .

      # The Docker login step is omitted here since it's not required for just building.
